### PR TITLE
Prefect utils fix resultrecord

### PR DESCRIPTION
**Pull request by zulissimeta**
## Summary of Changes

The resolve_futures_to_results seems to have a bug when the result is a "ResultRecord" rather than a "BaseResult". This came up when running a simple phonon flow:

```python
from quacc.recipes.emt.phonons import phonon_flow
from ase.build import bulk

cu_bulk = bulk('Cu')
phonon_flow(cu_bulk)
```

This change handles the case, and adds the phonon flow above as a test case for prefect (nice since it has a bunch of subflows/jobs/etc.

### Requirements

- [x] My PR is focused on a [single feature addition or bugfix](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests#write-small-prs).
- [x] My PR has relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).
- [x] My PR is on a [custom branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository) (i.e. is _not_ named `main`).

Note: If you are an external contributor, you will see a comment from [@buildbot-princeton](https://github.com/buildbot-princeton). This is solely for the maintainers.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Andrew-S-Rosen** [comment]
@zulissimeta: Thanks! Good catch. This is the function adapted from the upstream Prefect, right? If so, should we be opening an issue there to mark it?

**Comment by zulissimeta** [comment]
> @zulissimeta: Thanks! Good catch. This is the function adapted from the upstream Prefect, right? If so, should we be opening an issue there to mark it?

Yup - not sure this is common though - it only happens because we're chaining subflows to job which is perhaps less common in prefect?

**Comment by Andrew-S-Rosen** [comment]
> Yup - not sure this is common though - it only happens because we're chaining subflows to job which is perhaps less common in prefect?

I think that would still be valid prefect though, so I'd classify it as a bug. Ultimately, I would like to excise this custom patching from quacc entirely, but until I have someone to do that, we shall merge...

**Pull request merged**
