### PR TITLE
Q-Chem recipe redesign

### LINKED ISSUE #1112: More user-friendly handling of `QchemDictSet` parameters in Q-Chem recipes
### What new feature would you like to see?

As discussed with @samblau, currently, it is not possible to easily swap out a lot of the `QchemDictSet` parameters in the Q-Chem recipes. For instance, if you want to set the `custom_smd`, it's not easy to do.

Really, this is a general problem. A better solution would look like the following:

Changes:
- Remove `pcm_dielectric` kwarg
- Remove `smd_solvent` kwarg
- Remove `overwrite_inputs` kwarg
- Add `qchemdictset_params` kwarg

This is more in line with how other recipes, e.g. ORCA, operate. A sketch is below.

```python
@job
def static_job(
    atoms: Atoms,
    charge: int,
    spin_multiplicity: int,
    method: str = "wb97mv",
    basis: str = "def2-tzvpd",
    scf_algorithm: str = "diis",
    qchemdictset_params: dict | None = None,
    n_cores: int | None = None,
    copy_files: list[str] | None = None,
) -> RunSchema:

    qchemdictset_params = qchemdictset_params or {}
    default_qchemdictset_params = {"max_scf_cycles": 200 if scf_algorithm.lower() == "gdm" else None,
                             "nbo_params": {"version": 7} if SETTINGS.QCHEM_NBO_EXE else None}

    qchem_input_params = merge_dicts(default_qchemdictset_params, qchemdictset_params) # from quacc.utils.dicts

    defaults = {
        "basis_set": basis,
        "scf_algorithm": scf_algorithm,
        "method": method,
        "charge": charge,
        "spin_multiplicity": spin_multiplicity,
        "cores": n_cores or multiprocessing.cpu_count(),
        "qchem_input_params": qchem_input_params,
    }

    return _base_job(
        atoms,
        charge,
        spin_multiplicity,
        defaults=defaults,
        additional_fields={"name": "Q-Chem Static"},
        copy_files=copy_files,
    )
```

### PR DESCRIPTION
**Pull request by Andrew-S-Rosen**
This is a general overhaul of the Q-Chem recipes. There are many reasons why a redesign is necessary. From a usability perspective, the recipes are largely inconsistent with other recipes in `quacc`. Some input parameters of interest are also entirely inaccessible by the recipes, limiting flexibility for the user. It also relies heavily on knowledge of the Pymatgen `QchemDictSet` kwargs, which I consider undesirable (although we should support it of course).

This PR should resolve all those issues (and closes #1112) while still retaining all the features of the original recipes.

Edit: Alright, this is done!! But I am holding off on merging this until I run some production tests. If you're reading this and find this PR to be important to you, feel free to ping me.

### CODE REVIEW

**Comment by Andrew-S-Rosen** [comment]
Alright, this is done!! But I am holding off on merging this until I run some production tests. If you're reading this and find this PR to be important to you, feel free to ping me.

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Andrew-S-Rosen** [comment]
@buildbot-princeton: verified.

**Comment by Andrew-S-Rosen** [comment]
@samblau: While not time-sensitive, it would be great to get your opinion on this at some point. I know you were just complaining about changes to quacc, but it reminded me that this PR exists and that I would --- eventually --- very much like to update the Q-Chem recipes for many reasons.

First, a few caveats:
- If this gets merged, it will be merged as a beta (e.g. `recipes/qchem_beta`) for a period of time.
- The Q-Chem recipes you're using will still be there until I have your permission to deprecate them (e.g. after your project is fully done).
- Don't worry. I'm not doing anything to break your code with this. That said, we should continue to strive for improvement.

# Overview

The purpose of this PR is multi-fold.

1. There was the issue raised in #1112 that not all `QchemDictSet` params were directly accessible in the pre-existing recipes because they had to be enumerated as recipe kwargs.
2. There is a pretty stark contrast in how the Q-Chem recipes are constructed and how every other recipe in quacc is constructed, making it a bit difficult to use across codes and to maintain. 
3. The recipes only make sense to users if they are already familiar with `QChemDictSet`, which (for me) is not ideal.
5. Overall, there was some valuable refactoring that could/should be done.

## Example

### Minimal

A geometry optimization is performed, as usual. There is nothing fancy here.

```python
from quacc.recipes.qchem.core import relax_job
from ase.build import molecule

output = relax_job(molecule("N2"))
```

### QchemDictSet

Your `QchemDictSet` kwargs still work, I promise!

```python
from quacc.recipes.qchem.core import relax_job
from ase.build import molecule

output = relax_job(molecule("N2"), qchem_dict_set_params = {"solvent": "water"})
```

### Standard input

The recipes were made such that one can supply parameters without knowing anything about the `QChemDictSet`. It uses the kwargs from `QCInput`.

```python
from quacc.recipes.qchem.core import relax_job
from ase.build import molecule

output = relax_job(molecule("N2"), rem = {"SCF_CONVERGENCE": 1e-4})
```

Importantly, there is none of that `calc_swaps` nonsense. I stripped it from everywhere in quacc based on your feedback. You're welcome. 😂

## Summary

In essence, the recipes take a **kwargs that are passed to the `QChem` calculator. The `QChem` calculator supports all the kwargs in `QCInput` _and_ a special `qchem_dict_set_params` kwarg that can be used to instantiate a `QChemDictSet`. When both are used together, the two input files will be merged, with the input file parameters from the `QChemDictSet` taking priority.

This should, ideally, be the best of both worlds. It allows users who are only familiar with Q-Chem from the Q-Chem manual to easily specify input parameters how they please (since `QCInput` makes very cleanly and directly to the input file). At the same time, it allows for automatic setting of "complex" series of input parameters via `QChemDictSet` for ease-of-use. I know we have a bit of a difference of opinion on this and how we view the tools we ship, and that's okay. But I also hope that this proposal satisfies both parties to a fair degree.

I am certainly happy to get any feedback. The tests pass, which I've largely retained from before. However, I would like to add the HPC tests that will run on each PR, and that might reveal a few bugs left to sort out.

**Comment by Andrew-S-Rosen** [comment]
Merging this now so I can ensure I don't break it, but it's merged under `_qchem_beta` to keep the existing `qchem` recipes in tact.

**Pull request merged**
