### PR TITLE
Better defaults for Espresso recipes

### PR DESCRIPTION
**Pull request by tomdemeyere**
## Summary of Changes

Following our discussions, some better default from Espresso

These parameters aim to just 'work' for any systems you can throw. These are *very* far from optimal, for optimal parameters presets are available.

### Checklist

- [ ] I have read the ["Guidelines" section](https://quantum-accelerators.github.io/quacc/dev/contributing.html#guidelines) of the contributing guide. Don't lie! 😉
- [ ] My PR is on a custom branch and is _not_ named `main`.
- [ ] I have added relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).

### Notes

- Your PR will likely not be merged without proper and thorough tests.
- If you are an external contributor, you will see a comment from [@buildbot-princeton](https://github.com/buildbot-princeton). This is solely for the maintainers.
- When your code is ready for review, ping one of the [active maintainers](https://quantum-accelerators.github.io/quacc/about/contributors.html#active-maintainers).

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Andrew-S-Rosen** [comment]
Thanks, @tomdemeyere! This makes sense to me. One question: since there are some parameters here repeated between recipes and it's a bit bulky, do we want to factor some of them out at the top of the module like in the ONETEP recipes? Pros: Prevents code duplication; Cons: Takes another few seconds for the user to identify all the defaults.

https://github.com/Quantum-Accelerators/quacc/blob/ee3d9e79bdff93250929a0192f703e42de078399/src/quacc/recipes/onetep/core.py#L21-L28

**Comment by tomdemeyere** [comment]
@Andrew-S-Rosen Ha! I am working on that right now 😅 I actually made a separated `defaults.py` in the recipe folder? I had in mind to make it easier for users to have a look at them? Your say

**Comment by Andrew-S-Rosen** [comment]
I think that can make sense. My suggestion would be:
- If the defaults are only used in that module, it makes sense to have it at the top.
- If the defaults are used across modules (or likely _would_ be if new recipes were added), perhaps a dedicated `defaults.py` module makes sense. Let's call it `_defaults.py` though to indicate that this isn't a set of recipes, just like we do for `_base.py`.

But I'm flexible here.

**Comment by tomdemeyere** [comment]
This should be ok to go if you are happy with it

**Comment by Andrew-S-Rosen** [comment]
Thank you! Auto-merging.

**Pull request merged**
