### PR TITLE
added pdos job and flow

### PR DESCRIPTION
**Pull request by Nekkrad**
## Summary of Changes
Implemented a pdos job and a pdos flow (use of projwfc.x binary). 

There are multiple files created and in theory I could create custom functions to read all the relevant information and store them in the result dictionary. Another option is to read the xml file via either a big custom function or the use of xml_to_dict python package but that means we have to add a new dependency.

### Checklist

- [x] I have read the ["Guidelines" section](https://quantum-accelerators.github.io/quacc/dev/contributing.html#guidelines) of the contributing guide. Don't lie! 😉
- [x] My PR is on a custom branch and is _not_ named `main`.
- [x] I have used `black`, `isort`, and `ruff` as described in the [style guide](https://quantum-accelerators.github.io/quacc/dev/contributing.html#style).
- [x] I have added relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Nekkrad** [comment]
1. It seems that projwfc.x has the same problem as dos.x which causes the test to fail. I have more recipes ready for the other binaries (bands.x and  fermi surface). Should I still open new PRs or should we try and see if we can get the binaries to work

2. Puzzled about the DeepSource problem. I understand what it says but it works fine. Should I ignore it?

**Comment by Andrew-S-Rosen** [comment]
New dependencies are okay because we can make the optional (https://github.com/Quantum-Accelerators/quacc/issues/1614). That said, my preference would be for dependencies that are actively maintained (xml_to_dict hasn't had a commit in 10 months).

No worries about the deepsource issue. It's a bug I've reported to their team. I'll disable that error message over the repo later.

Regarding the binary, that's odd. I personally don't want to merge in code without passing tests, so we will probably need to either: figure out how to solve it, work around it, or (if we absolutely must) mock the Espresso call.

**Comment by Nekkrad** [comment]
> Regarding the binary, that's odd. I personally don't want to merge in code without passing tests, so we will probably need to either: figure out how to solve it, work around it, or (if we absolutely must) mock the Espresso call.

So the error seems to be related to some missing library (as in dos.x ) . I will try to conda install qe instead of my compiled one to see what happens.

**Comment by tomdemeyere** [comment]
Can you give here the result of `ldd $(which pw.x)` ?

**Comment by Nekkrad** [comment]
> Can you give here the result of `ldd $(which d

**Pull request closed without merging**
