### PR TITLE
Small changes in copy_decompress_files

### PR DESCRIPTION
**Pull request by tomdemeyere**
## Summary of Changes

Attempt to fix https://github.com/Quantum-Accelerators/quacc/issues/1933

### Checklist

- [x] I have read the ["Guidelines" section](https://quantum-accelerators.github.io/quacc/dev/contributing.html#guidelines) of the contributing guide. Don't lie! 😉
- [x] My PR is on a custom branch and is _not_ named `main`.
- [ ] I have added relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).

### Notes

- Your PR will likely not be merged without proper and thorough tests.
- If you are an external contributor, you will see a comment from [@buildbot-princeton](https://github.com/buildbot-princeton). This is solely for the maintainers.
- When your code is ready for review, ping one of the [active maintainers](https://quantum-accelerators.github.io/quacc/about/contributors.html#active-maintainers).

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Andrew-S-Rosen** [comment]
Thanks for the issue report and bug fix, @tomdemeyere! This is a good catch. To really be sure I don't screw this up, we should also add a test to https://github.com/tomdemeyere/quacc/blob/fix_copy_decompress/tests/core/utils/test_files.py for good measure with the **/name.* type pattern.

**Comment by Andrew-S-Rosen** [comment]
Thanks, @tomdemeyere! I think I'm fine with it. Later today, I'll just play around with a few edge cases locally to see if anything goes screwy that I need to address. I'll merge it then.

**Comment by Andrew-S-Rosen** [comment]
Thanks! This looks good and makes more sense than my approach anyway. 👍

**Pull request merged**
