### PR TITLE
Small bugfix for async prefect functions

### PR DESCRIPTION
**Pull request by zulissimeta**
## Summary of Changes

This provides a small bug fix for the recent patch to how prefect flows are handled. The prior methods only worked for sync flows.

### Requirements

- [x] My PR is focused on a [single feature addition or bugfix](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests#write-small-prs).
- [x] My PR has relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).
- [x] My PR is on a [custom branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository) (i.e. is _not_ named `main`).

Note: If you are an external contributor, you will see a comment from [@buildbot-princeton](https://github.com/buildbot-princeton). This is solely for the maintainers.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Andrew-S-Rosen** [comment]
@zulissimeta: Thank you! I have never used async flows.

Before merging, two questions:
1. Do we also need this for subflows, or no?
2. Would it be possible to add a minimal async test? I would like to ensure that upstream changes to Prefect do not break how we are handling our flows.

**Comment by zulissimeta** [comment]
> @zulissimeta: Thank you! I have never used async flows.
> 
> Before merging, two questions:
> 
> 1. Do we also need this for subflows, or no?
> 2. Would it be possible to add a minimal async test? I would like to ensure that upstream changes to Prefect do not break how we are handling our flows.

@Andrew-S-Rosen Good suggestion! Updated with some tests, and caught another bug.

**Comment by Andrew-S-Rosen** [comment]
@zulissimeta: Thank you again for this PR! I am mostly going to take this on faith since I'm not too familiar with the async work. However, it would be really helpful if we could increase the coverage on this PR. Would this be possible? Retaining the high code coverage of the repo is extremely helpful for me in maintaining this package.

**Comment by Andrew-S-Rosen** [comment]
Thank you, @zulissimeta! Merging but opening an issue to record the need to move things upstream: https://github.com/Quantum-Accelerators/quacc/issues/2473

**Pull request merged**
