### PR TITLE
Common flow for elastic constants calculations

### PR DESCRIPTION
**Pull request by Nekkrad**
## Summary of Changes

I have implemented a common recipe to generate and calculate properties of deformed structures to obtain elastic constants.
I have also implemented and tested this flow for the EMT calculator. The code is heavily inspired by the slabs flow. 

### Checklist

- [x] I have read the ["Guidelines" section](https://quantum-accelerators.github.io/quacc/dev/contributing.html#guidelines) of the contributing guide. Don't lie! 😉
- [x] My PR is on a custom branch and is _not_ named `main`.
- [x] I have used `black`, `isort`, and `ruff` as described in the [style guide](https://quantum-accelerators.github.io/quacc/dev/contributing.html#style).
- [x] I have added relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).

## Summary by CodeRabbit

- **New Features**
	- Added a new recipe "EMT Bulk to Deformations" to the user documentation.
	- Introduced utility functions for generating deformed structures from bulk atoms.
	- Introduced a common elastic constants workflow for generating and relaxing deformed structures, with optional static calculations.
- **Documentation**
	- Expanded the recipes list in the user documentation.
- **Tests**
	- Added tests for validating the functionality of creating deformations from a bulk atomic structure.
	- Introduced a test for elastic jobs using the EMT potential on a bulk copper structure.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Review by Andrew-S-Rosen — COMMENTED** [review]
Thanks, @Nekkrad! This looks great. Just a few minor comments from me.

Not for this PR, but just for your own reference, you may find the code in [this module](https://github.com/materialsvirtuallab/matcalc/blob/main/matcalc/elasticity.py) in `matcalc` helpful for the post-processing.

**Comment by Nekkrad** [comment]
> Thanks, @Nekkrad! This looks great. Just a few minor comments from me.
> 
> Not for this PR, but just for your own reference, you may find the code in [this module](https://github.com/materialsvirtuallab/matcalc/blob/main/matcalc/elasticity.py) in `matcalc` helpful for the post-processing.

This is something I wanted to ask, should we include some of those post-processing into the result schema or do we leave the post-processing to the user?

**Comment by Andrew-S-Rosen** [comment]
> > Thanks, @Nekkrad! This looks great. Just a few minor comments from me.
> > Not for this PR, but just for your own reference, you may find the code in [this module](https://github.com/materialsvirtuallab/matcalc/blob/main/matcalc/elasticity.py) in `matcalc` helpful for the post-processing.
> 
> This is something I wanted to ask, should we include some of those post-processing into the result schema or do we leave the post-processing to the user?

For initial implementations, it is helpful to do what you've done thus far --- leave it to the user. If you find yourself using this recipe a bunch though, by all means, we can/should open a PR to add a step in the `Flow` that does post-processing of the final results so that the user doesn't have to think about it at all.

**Comment by Andrew-S-Rosen** [comment]
@Nekkrad Don't worry too much about the `coderabbitai`. I wanted to try it out and see what it did. Seems useful but perhaps too chatty....... 😅

**Pull request merged**
