### PR TITLE
Issues with the grid_phonon_flow and custom decorators when using Parsl

### PR DESCRIPTION
**Pull request by tomdemeyere**
## Summary of Changes

It seems that the "job within a job" concept is not well appreciated by Parsl when using custom executors (redecorated jobs). Leading to problems as mentioned in #1852

Changing this `job` (_ph_recover_job) to a `subflow` and removing strip_decorators does make things work. We have now to understand how this can possibly affect other workflow engines.

### Checklist

- [ ] I have read the ["Guidelines" section](https://quantum-accelerators.github.io/quacc/dev/contributing.html#guidelines) of the contributing guide. Don't lie! 😉
- [ ] My PR is on a custom branch and is _not_ named `main`.
- [ ] I have added relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).

### Notes

- Your PR will likely not be merged without proper and thorough tests.
- If you are an external contributor, you will see a comment from [@buildbot-princeton](https://github.com/buildbot-princeton). This is solely for the maintainers.
- When your code is ready for review, ping one of the [active maintainers](https://quantum-accelerators.github.io/quacc/about/contributors.html#active-maintainers).

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Andrew-S-Rosen** [comment]
I understand the bug now. You are updating the decorator to the `quacc.recipes.espresso.phonons.phonon_job.ph_recover_job`, but that function does not have a decorator associated with it. It is a pure function. What really needs to happen is that the decorator to `_ph_recover_job` needs to be updated.

**Comment by tomdemeyere** [comment]
>> What really needs to happen is that the [decorator](https://github.com/Quantum-Accelerators/quacc/blob/89e1b9dda91fc6835a2de8f7e1dc83612b698a3b/src/quacc/recipes/espresso/phonons.py#L363) to _ph_recover_job needs to be updated.

I tried to do this, but somehow it was still throwing the same error?

``` python

    pw_job, ph_init_job, ph_job, ph_recover_job = customize_funcs(
        ["relax_job", "ph_init_job", "ph_job", "ph_recover_job"],
        [relax_job, phonon_job, phonon_job, phonon_job],
        parameters=job_params,
        decorators=job_decorators,
    )

    _ph_recover_custom = redecorate(_ph_recover_job, job_decorators.get("ph_recover_job", job()))

```

**Comment by Andrew-S-Rosen** [comment]
Your example doesn't update the `ph_recover_job`.

```python
    pw_job, ph_init_job, ph_job, ph_recover_job = customize_funcs(
        ["relax_job", "ph_init_job", "ph_job", "ph_recover_job"],
        [relax_job, phonon_job, phonon_job, phonon_job],
        parameters=job_params,
        decorators=job_decorators,
    )
```

Here, you are updating the `phonon_job` function and assigning it to the variable `ph_recover_job`. You need to pass the function to decorate as the second `list`. The name in the first list is simply for user-facing querying purposes.

**Comment by tomdemeyere** [comment]
It seems like the last job (recover job) is actually re-doing everything instead of reading files. This is probably due to file not being copied

I modified one test to make sure that Quacc catch this. I will fix it when I got the time

**Comment by Andrew-S-Rosen** [comment]
> It seems like the last job (recover job) is actually re-doing everything instead of reading files. This is probably due to file not being copied
> 
> I modified one test to make sure that Quacc catch this. I will fix it when I got the time

Good idea for the test. Makes sense as a potential culprit.

The `@subflow` vs. `@job` issue is still on my radar. I'm hoping to do a deeper dive on your open issues around this weekend or so. 👍 Currently drowning in a sea of grant proposals, some of which would hopefully secure funds for a software engineer to help out with quacc if successful!

**Comment by Andrew-S-Rosen** [comment]
@tomdemeyere: If you keep the original `@job` (i.e. don't switch to `@subflow`) and simply remove the `strip_decorator()` call, does that work? My understanding of the code suggests this would resolve your problems because you would no longer be stripping the decorator that you pre-customized. If that works, let's go with that approach.

**Comment by Andrew-S-Rosen** [comment]
Actually, scratch my comment. That would require the use of the `@subflow` decorator as you implemented.

I'll go ahead and merge this then, although I may return to it in the future.

**Pull request merged**
