### PR TITLE
Improve NewtonNet recipes tests

### PR DESCRIPTION
**Pull request by kumaranu**
- [x] I have read the [Developer Guide](https://quantum-accelerators.github.io/quacc/dev/contributing.html). Don't lie! 😉
- [x] My PR is on a custom branch and is _not_ named `main`.
- [x] I have added relevant unit tests. Note: Your PR will likely not be merged without proper tests.

### CODE REVIEW

**Comment by kumaranu** [comment]
I am working on running transition state (Sella) calculation with calc_kwargs. I most likely won't change much here, but, let me see.
Nevertheless, I have changed the tests for NewtonNet to include the cases I am interested in here.

**Comment by Andrew-S-Rosen** [comment]
Hi @kumaranu. It looks like your branch is quite out-of-sync with the `main` branch. Please make sure that the PR only has changes you intend to make. Also, please update the title of the PR accordingly. Thanks! Let me know when it's done and ready for review

**Comment by kumaranu** [comment]
@Andrew-S-Rosen 
I talked with you yesterday regarding my problems of not being able to run my calculations using `jobflow` and you solved my problem by suggesting that I should uninstall the `covalent` library. Doing so enabled `SETTINGS.WORKFLOW_ENGINE` to `jobflow` as it didn't have multiple options. My jobs are able to connect to `jobflow` now.

Nevertheless, my earlier problem of having the transition state calculations running really slow for a few geometries still exists. To confirm whether this issue exists only inside quacc, I ran those calculations outside of quacc and I did not face the slowness in the transition state calculations.

I have attached some files here to hopefully give more context here:

- prod.txt is a Python file.
- config.txt is a toml file.
- The others are XYZ files.
- I have changed their extensions to be able to upload them here.

[config30.txt](https://github.com/Quantum-Accelerators/quacc/files/13231262/config30.txt)
[prod.txt](https://github.com/Quantum-Accelerators/quacc/files/13231263/prod.txt)
[261.txt](https://github.com/Quantum-Accelerators/quacc/files/13231264/261.txt)
[193.txt](https://github.com/Quantum-Accelerators/quacc/files/13231265/193.txt)
[182.txt](https://github.com/Quantum-Accelerators/quacc/files/13231266/182.txt)
[082.txt](https://github.com/Quantum-Accelerators/quacc/files/13231267/082.txt)
[069.txt](https://github.com/Quantum-Accelerators/quacc/files/13231268/069.txt)
[068.txt](https://github.com/Quantum-Accelerators/quacc/files/13231269/068.txt)

**Comment by Andrew-S-Rosen** [comment]
@kumaranu: Thanks. Can you please open an issue report?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Andrew-S-Rosen** [comment]
I'm going to close this as stale.

**Pull request closed without merging**
