### PR TITLE
Support special Parsl keywords

### PR DESCRIPTION
**Pull request by tomdemeyere**
## Summary of Changes

Closes https://github.com/Quantum-Accelerators/quacc/issues/1886.

Adding `@wraps` does not work, special keywords are not passed to Parsl correctly in this case (I don't know why).

To perform proper testing, an `HighThroughputExecutor` will have to be loaded in the test.
### Checklist

- [x] I have read the ["Guidelines" section](https://quantum-accelerators.github.io/quacc/dev/contributing.html#guidelines) of the contributing guide. Don't lie! 😉
- [x] My PR is on a custom branch and is _not_ named `main`.
- [x] I have added relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).

### Notes

- Your PR will likely not be merged without proper and thorough tests.
- If you are an external contributor, you will see a comment from [@buildbot-princeton](https://github.com/buildbot-princeton). This is solely for the maintainers.
- When your code is ready for review, ping one of the [active maintainers](https://quantum-accelerators.github.io/quacc/about/contributors.html#active-maintainers).

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Andrew-S-Rosen** [comment]
Thanks for this PR, @tomdemeyere!

>Adding @wraps does not work, special keywords are not passed to Parsl correctly in this case (I don't know why).

Apologies, as I should have been more direct: did you try `@wraps(_func)` immediately above the definition for `wrapper`? It should not be `@wraps` but rather `@wraps(_func)`.

**Comment by tomdemeyere** [comment]
@Andrew-S-Rosen 

Yes, It does not work unfortunately Parsl does not create the environment  variable in this case

**Comment by Andrew-S-Rosen** [comment]
@tomdemeyere: Let me know when this is ready to go with the monitoring name fix. 👍 Thanks!

**Comment by tomdemeyere** [comment]
Here you go, ruff will complain that keywords aren't being used.

Thanks for taking care of the code duplication!

**Comment by Andrew-S-Rosen** [comment]
Thanks! I will work on this shortly. Nothing else needed from you on this. I'll take care of ruff by adding in the `# noqa` comment lines.

**Comment by Andrew-S-Rosen** [comment]
I'm removing support for `stdout` and `stderr` because they only seem to work with `@bash_app` calls.

**Pull request merged**
